app/v2/controllers/campaign/dashboard.js, app/v2/controllers/contribution/page.js, app/v2/directives/contribution-card.js, app/v2/directives/contribution-contextual-items.js, app/v2/partials/directives/contribution-card.html, app/v2/partials/directives/contribution-contextual-items.html, app/v2/partials/proposal/page.html
=> Disable editing functionalities if the campaign component key is not IDEAS or PROPOSALS.

app/v2/stylesheets/main.scss
=> Fix menu styles.

app/app.js, app/partials/footer.html, app/v2/directives/reset-style.js, app/v2/partials/home.html
ref #390
ref #404 (already included)
=> Styles of the landing page are updated. URLs: #/v2/home and #/.

Gruntfile.js, app/controllers/contributions.js, index.html
=> Fix grunt build babel integration

app/services/appCivistService.js, app/services/loginService.js, app/v2/controllers/main.js, app/v2/directives/contribution-form.js, app/v2/partials/navigation-bar-large.html, app/v2/stylesheets/main.scss
- Sync my working groups based on current campaign
- In the list of Working Groups for creating a PROPOSAL, make sure they
contain only the list of groups of the currentCampaign
refs #515
=> Emphasize currentCampaign and workingGroup in sidebar

app/v2/controllers/campaign/dashboard.js, app/v2/directives/contribution-feedback-form.js, app/v2/partials/directives/contribution-feedback-form.html, app/v2/stylesheets/main.scss
=> Fix recaptcha in contribution feedback form

app/app.js, app/v2/controllers/contribution/page.js, app/v2/partials/proposal/page.html
=> Fix readonly URL

app/v2/stylesheets/main.scss
=> Fix input file css

app/v2/controllers/contribution/page.js, app/v2/directives/custom-field.js, app/v2/partials/directives/contribution-contextual-items.html, app/v2/partials/directives/custom-field.html, app/v2/partials/proposal/page.html, app/v2/stylesheets/main.scss, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
=> Display custom field values in proposal page

app/v2/partials/proposal/page.html
=> Fix etherpad iframe duplication

Gruntfile.js
=> Add missing fonts

app/services/appCivistService.js, app/v2/controllers/contribution/page.js
=> Show custom field values in public proposal page

app/v2/partials/directives/contribution-card.html
=> Fix contribution card height issue

app/v2/controllers/user/profile.js, app/v2/partials/user/profile.html, app/v2/stylesheets/main.scss, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
=> Preview selected picture in profile page

app/services/appCivistService.js, app/v2/controllers/contribution/page.js, app/v2/directives/contribution-feedback-panel.js, app/v2/partials/proposal/page.html
=> Show "Technical assessments" only if available in proposal public page

app/v2/directives/contribution-form.js, app/v2/directives/tags-field.js, app/v2/partials/campaign/dashboard.html, app/v2/partials/directives/contribution-form.html, app/v2/partials/directives/tags-field.html, app/v2/stylesheets/main.scss
=> Fix authors/themes filtering in contribution-form directive

app/services/appCivistService.js, app/services/loginService.js, app/v2/controllers/campaign/dashboard.js, app/v2/controllers/main.js, app/v2/directives/contribution-form.js, app/v2/partials/campaign/dashboard.html
=> Fix issues with current campaign's working groups caching

app/v2/controllers/campaign/dashboard.js, app/v2/directives/contribution-form.js, app/v2/directives/pagination-widget.js, app/v2/partials/directives/contribution-form.html
- Refactor contribution-form directive to use controllerAs property.
- Add event pagination:reloadCurrentPage to pagination-widget
refs #582
=> Update proposals list after creating a new one

app/app.js, app/v2/controllers/contribution/page.js, app/v2/controllers/main.js, app/v2/directives/contribution-card.js, app/v2/partials/directives/contribution-card.html, app/v2/partials/navigation-bar-large.html, app/v2/partials/proposal/page.html
=> Refactor working group and proposal path

app/v2/controllers/working-group/dashboard.js, app/v2/directives/contribution-form.js, app/v2/partials/directives/contribution-form.html, app/v2/partials/working-group/dashboard.html
=> Add new proposal button in WG dashboard

app/services/appCivistService.js, app/services/configService.js, app/v2/controllers/working-group/form.js, app/v2/directives/wgroup-contextual-items.js, app/v2/partials/directives/wgroup-contextual-items.html, app/v2/partials/working-group/form.description.html
TODO:
- configurations update is not working in the backend. It throws the given error
```
! @73l8di067 - Internal server error, for (PUT) [/api/space/5557/config] ->
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[NullPointerException: null]]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.6.jar:2.4.6]
at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.6.jar:2.4.6]
at play.core.j.JavaGlobalSettingsAdapter.play$core$j$JavaGlobalSettingsAdapter$$super$onError(JavaGlobalSettingsAdapter.scala:36) [play_2.11-2.4.6.jar:2.4.6]
at …
```
=> Feature#577

app/v2/directives/contribution-feedback-form.js, app/v2/partials/directives/contribution-feedback-form.html
=> Implement custom and hidden fields in feedback form.

app/services/appCivistService.js, app/v2/directives/contribution-feedback-form.js, app/v2/directives/contribution-form.js
=> Hide editor status bar (tinymce).

app/v2/controllers/assembly/home.js, app/v2/partials/assembly/home.html
=> CampaignID bugfix.

app/app.js, app/services/appCivistService.js, app/v2/controllers/campaign/dashboard.js, app/v2/controllers/main.js, app/v2/controllers/working-group/dashboard.js, app/v2/directives/discussion-panel.js, app/v2/partials/campaign/dashboard.html, app/v2/partials/navigation-bar-large-anonymous.html, app/v2/partials/navigation-bar-large.html, app/v2/partials/working-group/dashboard.html, assets/i18n/locale-en-US.json
Other working groups are added in the sidebar.
ref #396
=> Anonymous working group page is added.

app/v2/directives/contribution-form.js, app/v2/partials/directives/contribution-form.html
=> Fix hidden fields managemente in contribution form

.vscode/formatter.json, app/v2/directives/contribution-form.js, app/v2/partials/directives/contribution-form.html
This should be merged after https://github.com/socialappslab/appcivist-pb-client/pull/645
=> Feature#622

app/v2/controllers/main.js, app/v2/partials/navigation-bar-large.html
=> Fix sidebar issues

app/v2/partials/working-group/dashboard.html
=> Fix remaining conflict in working group dashboard

app/v2/directives/contribution-proposal-form.js, app/v2/partials/directives/contribution-proposal-form.html
=> Fix add attachment in proposal form

app/v2/controllers/working-group/dashboard.js, app/v2/directives/pagination-widget.js, app/v2/directives/proposals-ideas-searchbox.js, app/v2/partials/directives/pagination-widget.html, app/v2/partials/working-group/dashboard.html
=> Fix pagination and proposals-ideas-searchbox integration

app/v2/directives/contribution-card-themes.js, app/v2/directives/contribution-card.js, app/v2/partials/directives/contribution-card-themes.html, app/v2/partials/directives/contribution-card.html, app/v2/stylesheets/main.scss, index.html
=> Implemented contribution-card-themes component

app/v2/directives/contribution-form.js, assets/i18n/locale-es-ES.json
=> Fix ID deletion of existing emergent themes

app/v2/directives/proposals-ideas-searchbox.js, app/v2/partials/directives/proposals-ideas-searchbox.html
To clear currently applied filter, just click toggle button again.
refs #703
=> Fix filter toggle in proposals-ideas-searchbox

app/v2/directives/proposals-ideas-searchbox.js, app/v2/partials/campaign/dashboard.html, app/v2/partials/directives/contribution-feedback.html, app/v2/partials/directives/discussion-panel.html, app/v2/partials/directives/pagination-widget.html, app/v2/partials/working-group/dashboard.html, app/v2/stylesheets/dashboard.scss, app/v2/stylesheets/group-dashboard.scss, app/v2/stylesheets/main.scss, app/v2/stylesheets/pagination-widget.scss
=> Fix resizing of idea cards and max stack call issue

app/v2/directives/contribution-card.js, app/v2/directives/contribution-contextual-items.js, app/v2/directives/contribution-feedback.js, app/v2/directives/contribution-moderation-form.js, app/v2/partials/campaign/dashboard.html, app/v2/partials/directives/contribution-card.html, app/v2/partials/directives/contribution-contextual-items.html, app/v2/partials/directives/contribution-feedback.html, app/v2/partials/directives/contribution-moderation-form.html, app/v2/stylesheets/discussion-panel.scss, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json, index.html
=> Add basic moderation features to contribution cards

app/v2/controllers/campaign/dashboard.js, app/v2/controllers/contribution/page.js, app/v2/controllers/working-group/dashboard.js
=> Use campaign/working group/proposal page language in public site.

app/v2/mockups/navigation-bar-large.html, app/v2/mockups/navigation-bar.scss
https://github.com/socialappslab/appcivist-pb-client/pull/765 should be merged first.
=> Feature patterns#106

app/app.js, app/v2/mockups/dashboard.html, app/v2/mockups/dashboard.scss, app/v2/partials/main.html
https://github.com/socialappslab/appcivist-pb-client/pull/787 should be merged first
=> Feature patterns#121

app/app.js, app/v2/mockups/dashboard.html, app/v2/mockups/dashboard.scss, app/v2/mockups/navigation-bar.scss, app/v2/partials/main.html, app/v2/stylesheets/main.scss
https://github.com/socialappslab/appcivist-pb-client/pull/788 should be merged first.
=> Feature patterns#123

app/app.js, app/v2/mockups/dashboard.html, app/v2/mockups/dashboard.scss, app/v2/mockups/navigation-bar.scss, app/v2/partials/main.html, app/v2/stylesheets/main.scss
PR https://github.com/socialappslab/appcivist-pb-client/pull/784 should be merged first
=> Feature patterns#113

app/app.js, app/v2/mockups/dashboard.html, app/v2/mockups/dashboard.scss, app/v2/mockups/navigation-bar.scss, app/v2/partials/main.html, app/v2/stylesheets/main.scss
PR https://github.com/socialappslab/appcivist-pb-client/pull/785 should be merged first
=> Feature patterns#114

app/v2/directives/contribution-form.js
refs #777
Signed-off-by: Jorge Ramírez <jorgeramirez1990@gmail.com>
=> Add loading indicator for import feature

app/app.js, app/v2/mockups/newsletter-backend-template-no-activity.html, app/v2/mockups/newsletter-backend-template-with-activity.html, app/v2/mockups/newsletter-backend-template.scss, app/v2/stylesheets/main.scss
https://github.com/socialappslab/appcivist-pb-client/pull/791 should be merged first
=> Feature patterns#117

app/app.js, app/v2/mockups/newsletter-backend-template-no-activity.html, app/v2/mockups/newsletter-backend-template-proposal-stage.html, app/v2/mockups/newsletter-backend-template-with-activity.html, app/v2/mockups/newsletter-backend-template.scss, app/v2/stylesheets/main.scss
https://github.com/socialappslab/appcivist-pb-client/pull/791 should be merged first
=> Feature patterns#118

app/app.js, app/v2/mockups/newsletter-backend-template-no-activity.html, app/v2/mockups/newsletter-backend-template-proposal-stage.html, app/v2/mockups/newsletter-backend-template-text-only.html, app/v2/mockups/newsletter-backend-template-with-activity.html, app/v2/mockups/newsletter-backend-template.scss, app/v2/stylesheets/main.scss
https://github.com/socialappslab/appcivist-pb-client/pull/791 should be merged first
=> Feature patterns#119

app/css/app.css, app/v2/mockups/voting-modal.html, app/v2/mockups/voting-modal.scss, app/v2/partials/campaign/dashboard.html, app/v2/stylesheets/main.scss
refs socialappslab/appcivist-patterns#133
=> Added mockup for voting instructions modal

app/v2/controllers/assembly/home.js, app/v2/mockups/buttons.scss, app/v2/partials/assembly/home.html, app/v2/stylesheets/assembly.scss, app/v2/stylesheets/main.scss
=> Changes in assembly homepage

app/v2/controllers/user/profile.js, app/v2/partials/user/profile.html
One button for each assembly that has social-ideation-enable=TRUE config
=> Multiple buttons for connect to Social Ideation. 

app/v2/components/contribution-card-voting-control/contribution-card-voting-control.scss
Now it works on idea cards too.
refs #134
=> Fix for contribution voting controls style

app/css/app.css, app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html, app/v2/stylesheets/page_header.scss, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Every modal except 'Contributing Ideas' are enabled.
=> Implemented new topbar for contributions page

app/css/app.css, app/v2/controllers/working-group/dashboard.js, app/v2/partials/working-group/dashboard.html, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Added the toolbar with a button for assigned ideas and other for members.
The modal for assigned ideas works, but still can't get an API endpoint to add to WGs' resource space.
=> Added toolbar for Working Groups dashboard and modal for assigning ideas (still needs some work)

app/css/app.css, app/v2/partials/directives/contribution-card.html, app/v2/partials/working-group/dashboard.html, app/v2/stylesheets/card_header.scss, app/v2/stylesheets/main.scss, app/v2/stylesheets/ribbon.scss
Removed background for the contribution cards only on Working Groups dashboard and applied style and ribbons based on `contribution.status`
=> Modified style for WG cards (with ribbons too)

app/app.js, app/css/app.css, app/services/appCivistService.js, app/v2/components/contribution-embed-modal/contribution-embed-modal.html, app/v2/components/contribution-embed-modal/contribution-embed-modal.js, app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html, app/v2/stylesheets/buttons.scss, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json, index.html
The modal is implemented as a component. It takes an URL and posts it via service endpoint.
=> Implemented modal for embedding Gdoc/Etherpad

app/services/appCivistService.js, app/v2/controllers/working-group/dashboard.js, app/v2/partials/working-group/dashboard.html
Added resend invitation function and reload after invite
=> Changes to members modal

app/css/app.css, app/v2/components/add-resource-form/add-resource-form.js, app/v2/components/contribution-embed-modal/contribution-embed-modal.js, app/v2/components/session-modal/session-modal.js, app/v2/controllers/assembly/form.js, app/v2/controllers/assembly/home.js, app/v2/controllers/campaign/dashboard.js, app/v2/controllers/campaign/form.js, app/v2/controllers/contribution/all.js, app/v2/controllers/contribution/page.js, app/v2/controllers/login.js, app/v2/controllers/user/profile.js, app/v2/controllers/working-group/dashboard.js, app/v2/controllers/working-group/form.js, app/v2/directives/campaign-contextual-items.js, app/v2/directives/configure-ballot-form.js, app/v2/directives/contribution-contextual-items.js, app/v2/directives/contribution-feedback-form.js, app/v2/directives/contribution-feedback-panel.js, app/v2/directives/contribution-feedback.js, app/v2/directives/contribution-form.js, app/v2/directives/contribution-proposal-form.js, app/v2/directives/custom-field.js, app/v2/directives/discussion-panel.js, app/v2/directives/history-modal.js, app/v2/directives/nonmember-author-form.js, app/v2/directives/wgroup-contextual-items.js, docs/controllers_campaign_dashboard.js.html
A few were left unchanged because didn't had backend support, stuff like 'Password needs to be 11 letters or more' and so.
=> Changed Notify.show to show error.statusMessage instead of plain text if they originate from backend

app/css/app.css, app/services/appCivistService.js, app/v2/controllers/contribution/page.js, app/v2/directives/contribution-card.js, app/v2/directives/contribution-export.js, app/v2/partials/directives/contribution-contextual-items.html, app/v2/partials/directives/contribution-export.html, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json, index.html
Open the contextual menu of the contribution from the card view or the contribution page.
=> Added contextual menu item for exporting contributions

app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html
Reverts socialappslab/appcivist-pb-client#1079
=> Revert "Feature/1067 Partial merge"

app/v2/components/topbar-langpicker/topbar-langpicker.js, app/v2/directives/contribution-form.js
refs socialappslab/appcivist#53
=> Fix for wrong display language bug

app/app.js, app/services/appCivistService.js
New tabs from AppCivist now displays a public version of the resource instead of redirecting to old login page.
refs socialappslab/appcivist-pb-client#1145
=> Fix for new tabs

app/v2/controllers/contribution/page.js
This should resolve the issue on the UI. Needs the backend fix on socialappslab/appcivist-platform#868 to work.
Also quickfix for infinite peerdoc title polling even after leaving the page.
=> Fix for last updated format

app/v2/partials/directives/discussion-panel.html
Changed discussion.authors[0] by comment.authors[0]
=> Bug in the response to comment user profile box

app/v2/partials/campaign/dashboard.html, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Fix translation of type of contribution in the stats of campaign page
=> PR for Issue #1164

app/css/app.css, app/services/appCivistService.js, app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Includes also avoiding empty keywords
=> Multiple Choice Custom Fields for Headers

app/v2/controllers/contribution/page.js
This also fixed the reported bug. I just choose to also hide from the list the current authors and nonmemberauthors.
=> Current authors will not appear on authors dropdown anymore

app/services/appCivistService.js, app/v2/controllers/contribution/page.js, app/v2/directives/pagination-widget.js, app/v2/directives/proposals-ideas-searchbox.js, app/v2/partials/contribution/page.html, app/v2/partials/directives/pagination-widget.html, app/v2/partials/directives/proposals-ideas-searchbox.html, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Also uses the new 'creator' endpoint for the proposal page.
=> Added 'shared with me' filter

app/v2/partials/campaign/dashboard.html
Changed comment count in the campaign page
=> Changed comment count in the campaign page

app/v2/directives/discussion-panel.js, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
=> PR for issue #1165

app/v2/controllers/contribution/page.js
No attachment is removed in the process
=> Removing attachments from payload for updating contribution descriptions

app/v2/components/add-resource-form/add-resource-form.js, app/v2/components/contribution-embed-modal/contribution-embed-modal.js, app/v2/components/motivational-messages/motivational-messages.js, app/v2/controllers/contribution/page.js, app/v2/controllers/user/profile.js, app/v2/controllers/working-group/dashboard.js, app/v2/controllers/working-group/form.js, app/v2/directives/campaign-contextual-items.js, app/v2/directives/configure-ballot-form.js, app/v2/directives/contribution-contextual-items.js, app/v2/directives/contribution-feedback-form.js, app/v2/directives/contribution-form.js, app/v2/directives/contribution-moderation-form.js, app/v2/directives/contribution-proposal-form.js, app/v2/directives/wgroup-contextual-items.js, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-pt-BR.json
=> PR for issue #1218

app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html, app/v2/stylesheets/contributions-page.scss, assets/i18n/locale-de-DE.json, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-fr-CA.json, assets/i18n/locale-fr-FR.json, assets/i18n/locale-it-IT.json, assets/i18n/locale-pt-BR.json
Also added a red background color to the fields where there's an error as for #1277 asked.
=> Changed message when changing status returns field errors

app/v2/stylesheets/contributions-page.scss, app/v2/stylesheets/navigation-bar.scss
Fixing the actual header needs an element redesign, so we'll be skipping that for a later sprint.
=> Fixes for responsive design in contribution page

app/v2/controllers/working-group/dashboard.js, app/v2/partials/working-group/dashboard.html
Config is called `appcivist.working-group.allow-non-members-to-post-proposals`
=> Config for allowing non members to create proposals in working group

app/v2/controllers/working-group/dashboard.js, app/v2/partials/working-group/dashboard.html
The config key is `appcivist.working-group.hide-assigned-ideas === 'TRUE'`
=> Hide assigned ideas if there's a config

app/v2/partials/contribution/page.html, app/v2/stylesheets/contributions-page.scss, app/v2/stylesheets/navigation-bar.scss, app/v2/stylesheets/page_header.scss
Includes some responsive fixes.
=> Proposal page toolbar is sticky

app/v2/controllers/main.js
=> Update logout from profile redirection

app/v2/controllers/contribution/page.js, app/v2/partials/contribution/page.html, assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-pt-BR.json
=> Add checkbox button in contribution page

assets/i18n/locale-en-US.json, assets/i18n/locale-es-ES.json, assets/i18n/locale-es-PY.json, assets/i18n/locale-pt-BR.json
=> 1438 contribution source title
